In [1]:
import shapefile
import pandas as pd

# Load the Shapefile for Houston zip codes
sf = shapefile.Reader("tl_2020_us_zcta510/tl_2020_us_zcta510.shp")

# Get the index of the "ZCTA5CE10" field
zip_field_idx = [f[0] for f in sf.fields].index("ZCTA5CE10") - 1

# Define the coordinates of the bounding box for Houston
lon_min, lat_min = -95.7998, 29.5235
lon_max, lat_max = -95.2557, 30.1102

# Define the list of zip codes to plot
zip_codes = ['77002', '77003', '77004', '77005', '77006', '77007', '77008', '77009', '77010', '77011', '77012', '77013', '77014', '77015', '77016', '77017', '77018', '77019', '77020', '77021', '77022', '77023', '77024', '77025', '77026', '77027', '77028', '77029', '77030', '77031', '77032', '77033', '77034', '77035', '77036', '77037', '77038', '77039', '77040', '77041', '77042', '77043', '77044', '77045', '77046', '77047', '77048', '77049', '77050', '77051', '77053', '77054', '77055', '77056', '77057', '77058', '77059', '77060', '77061', '77062', '77063', '77064', '77065', '77066', '77067', '77068', '77069', '77070', '77071', '77072', '77073', '77074', '77075', '77076', '77077', '77078', '77079', '77080', '77081', '77082', '77083', '77084', '77085', '77086', '77087', '77088', '77089', '77090', '77091', '77092', '77093', '77094', '77095', '77096', '77098', '77099']

# Create a list of dictionaries to store the polygon coordinates for each zip code
zip_data = []
for zip_code in zip_codes:
    # Get the shape record for the zip code
    shape_records = sf.shapeRecords()
    shape_record = next(sr for sr in shape_records if sr.record[zip_field_idx] == zip_code)

    # Get the polygon coordinates for the zip code
    polygon = shape_record.shape.points

    # Create a dictionary with the zip code and its polygon coordinates
    zip_dict = {
        'Zip Code': zip_code,
        'Polygon Coordinates': polygon
    }

    # Append the dictionary to the list
    zip_data.append(zip_dict)

# Create a dataframe from the list of dictionaries
df = pd.DataFrame(zip_data)

# Show the dataframe
print(df)

   Zip Code                                Polygon Coordinates
0     77002  [(-95.388543, 29.729575999999998), (-95.388116...
1     77003  [(-95.367436, 29.744123), (-95.36685, 29.74488...
2     77004  [(-95.371729, 29.74673), (-95.370874, 29.74621...
3     77005  [(-95.44787, 29.727269999999997), (-95.447206,...
4     77006  [(-95.402844, 29.734313), (-95.402065, 29.7343...
..      ...                                                ...
91    77094  [(-95.71893, 29.784913), (-95.718744, 29.78491...
92    77095  [(-95.686371, 29.925853), (-95.686335, 29.9260...
93    77096  [(-95.509778, 29.659181), (-95.508443, 29.6591...
94    77098  [(-95.43023099999999, 29.733783), (-95.429265,...
95    77099  [(-95.55977299999999, 29.673119999999997), (-9...

[96 rows x 2 columns]

In [2]:
df

   Zip Code                                Polygon Coordinates
0     77002  [(-95.388543, 29.729575999999998), (-95.388116...
1     77003  [(-95.367436, 29.744123), (-95.36685, 29.74488...
2     77004  [(-95.371729, 29.74673), (-95.370874, 29.74621...
3     77005  [(-95.44787, 29.727269999999997), (-95.447206,...
4     77006  [(-95.402844, 29.734313), (-95.402065, 29.7343...
..      ...                                                ...
91    77094  [(-95.71893, 29.784913), (-95.718744, 29.78491...
92    77095  [(-95.686371, 29.925853), (-95.686335, 29.9260...
93    77096  [(-95.509778, 29.659181), (-95.508443, 29.6591...
94    77098  [(-95.43023099999999, 29.733783), (-95.429265,...
95    77099  [(-95.55977299999999, 29.673119999999997), (-9...

[96 rows x 2 columns]